# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c52ea8a842e3a3e9ba2383b00f526766220ffa9b005cee2f0e964d1512760a8babfceb7d5b5ba1cb4d2cfcd2ed4c58be1efbda4be0a7c4df61cd8526e7793839

test:
  secret_key_base: b80ce7a92aedd99bddb7e6153fc6a59d390523cdbbc13a9ac68ce1304c73ca171c4097794ebc8ec212d63e9c014d5590e5fe6c968680b188fb413da1784eb942

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
